Fixing tests
AcutronicRobotics/moveit2 pull request #56
Opened 2019-04-25 08:42 UTC by ahcorde

2019-04-25 08:47 UTC, vmayoral approved these changes

2019-04-25 08:48 UTC, vmayoral commented
Let's wait for the CI

2019-04-25 08:54 UTC, vmayoral requested changes
On a second look , this is actually not acceptable. You've changed the LOGGER names and that was agreed through a lot of iterations. Can you please revert this @ahcorde?

I mean, no changes to `LOGGER` variable names should be done.

2019-04-25 08:55 UTC, ahcorde commented
I can't otherwise it's not compiling

2019-04-25 08:56 UTC, vmayoral submitted a review, later dismissed

2019-04-25 08:56 UTC, vmayoral commented on moveit_core/background_processing/src/background_processing.cpp
> +        RCLCPP_DEBUG(LOGGER_BACKGROUND_PROCESSING, "Begin executing '%s'", action_name.c_str());
This shouldn't be reverted.

2019-04-25 08:56 UTC, vmayoral commented on moveit_core/background_processing/src/background_processing.cpp
> +rclcpp::Logger LOGGER_BACKGROUND_PROCESSING = rclcpp::get_logger("background_processing");
This shouldn't be changed either.

2019-04-25 08:56 UTC, vmayoral commented on moveit_core/background_processing/src/background_processing.cpp
> +        RCLCPP_ERROR(LOGGER_BACKGROUND_PROCESSING, "Exception caught while processing action '%s': %s", action_name.c_str(), ex.what());
etc.

2019-04-25 08:57 UTC, vmayoral commented
> I can't otherwise it's not compiling

Let's look at this together.

2019-04-25 09:05 UTC, LanderU commented
```bash
libmoveit_robot_model.a(robot_model.cpp.o): In function `moveit::core::RobotModel::constructShape(urdf::Geometry const*)':
robot_model.cpp:(.text+0x9116): undefined reference to `shapes::Sphere::Sphere(double)'
robot_model.cpp:(.text+0x918d): undefined reference to `shapes::Box::Box(double, double, double)'
robot_model.cpp:(.text+0x91d8): undefined reference to `shapes::Cylinder::Cylinder(double, double)'
robot_model.cpp:(.text+0x925d): undefined reference to `shapes::createMeshFromResource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)'
libmoveit_robot_model.a(link_model.cpp.o): In function `moveit::core::LinkModel::setGeometry(std::vector<std::shared_ptr<shapes::Shape const>, std::allocator<std::shared_ptr<shapes::Shape const> > > const&, std::vector<Eigen::Transform<double, 3, 1, 0>, Eigen::aligned_allocator<Eigen::Transform<double, 3, 1, 0> > > const&)':
link_model.cpp:(.text+0x720): undefined reference to `shapes::computeShapeExtents(shapes::Shape const*)'
link_model.cpp:(.text+0x77e): undefined reference to `typeinfo for shapes::Mesh'
link_model.cpp:(.text+0x785): undefined reference to `typeinfo for shapes::Shape'
collect2: error: ld returned 1 exit status
make[2]: *** [robot_model/test_moveit_robot_model] Error 1
```

2019-04-25 09:26 UTC, LanderU commented
OS X:

```bash
CMake Error in robot_model/CMakeLists.txt:
  Imported target "resource_retriever::resource_retriever" includes
  non-existent path
    "/Users/osrf/jenkins-agent/workspace/packaging_osx/ws/install/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
```

2019-04-27 07:51 UTC, vmayoral commented
@ahcorde, this is till failing. What's the status?

2019-05-02 11:18 UTC, anasarrak commented on moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
> +    printf("Waiting for Robot model topic! Did you remap '%s'?\n", robot_description.c_str());
Please lets remove the printf and use RCLCPP_WARN or RCLCPP_INFO.

2019-05-02 11:19 UTC, anasarrak commented on moveit_ros/planning/rdf_loader/src/rdf_loader.cpp
> +    printf("Waiting for Robot model semantic topic! Did you remap '%s'?\n", std::string(robot_description + "_semantic").c_str());
Same as https://github.com/AcutronicRobotics/moveit2/pull/56/commits/2cf435bf4dc98876a1253d3d5c53a28ebf8f15dd#r280375688

2019-05-02 11:22 UTC, anasarrak commented on moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp
> +  printf("RobotModelLoader Node is not declare!!\n");
Same as https://github.com/AcutronicRobotics/moveit2/pull/56/commits/2cf435bf4dc98876a1253d3d5c53a28ebf8f15dd#r280375688

2019-05-02 11:23 UTC, anasarrak commented on moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp
> +  printf("RobotModelLoader Node is not declare!!\n");
same https://github.com/AcutronicRobotics/moveit2/pull/56/commits/2cf435bf4dc98876a1253d3d5c53a28ebf8f15dd#r280375688

2019-05-02 11:28 UTC, anasarrak commented on moveit_core/robot_state/src/robot_state.cpp
>    builtin_interfaces::msg::Time tm = clock_ros.now();
```suggestion
   builtin_interfaces::msg::Time tm = rclcpp::Clock().now();
```
What about this change?

2019-05-07 15:30 UTC, ahcorde commented
CI is configure with Crystal patch4, but we are using dashing (beta). We need to fix CI

2019-05-15 14:54 UTC, vmayoral commented
@ahcorde, shall we close this one?

2019-05-15 14:55 UTC, ahcorde commented
sure

2019-05-15 14:55 UTC, closed without merging