Port planning request adapter plugins
AcutronicRobotics/moveit2 pull request #74
Opened 2019-05-16 14:22 UTC by anasarrak

Please don't merge, I'm still trying to fix the test

2019-05-16 14:42 UTC, anasarrak commented
Everything should work now @ahcorde

2019-05-21 09:33 UTC, ahcorde requested changes

2019-05-21 09:33 UTC, ahcorde commented on moveit_ros/planning/planning_request_adapter_plugins/src/fix_workspace_bounds.cpp
> +  void initialize(std::shared_ptr<rclcpp::Node>& node)
I think it's a good idea to add to all of them the method initialize.

2019-05-23 13:08 UTC, ahcorde commented
close this PR, but oppening https://github.com/AcutronicRobotics/moveit2/pull/85

2019-05-23 13:08 UTC, closed without merging